spring.application.name=Government-Welfare-Advisory-System
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7vnqa3tqb8s73fi0eg0-a.oregon-postgres.render.com/welfare_db_afkb

spring.datasource.username=welfare_user

spring.datasource.password=ypL6HSY1Ht3ZQvQUaYliyRrqwjRx9dbP

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# IMPORTANT (ADD THIS)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

ml.api.url=${ML_API_URL:http://localhost:5000/predict}