# ===============================
# Application Info
# ===============================
spring.application.name=Government-Welfare-Advisory-System
server.port=8080

# ===============================
# PostgreSQL Database (Render)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d76t87ea2pns73ecmhgg-a.oregon-postgres.render.com/welfare_db_0njv
spring.datasource.username=welfare_user
spring.datasource.password=WOX2OEwkjWBRsqsPZxE0RpWcpkyRzzMn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# ML API Configuration
# ===============================
ml.api.url=${ML_API_URL:http://localhost:5000/predict}